CanellaPrueba/MVC/Models/ErrorViewModel.cs
namespace MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CanellaPrueba/MVC/Models/GarajeViewModel.cs
namespace MVC.Models
{
    public class GarajeViewModel
    {

        public int IdGaraje { get; set; }
        public string Nombre { get; set; } = null!;
    }
}

CanellaPrueba/MVC/Models/VehiculoViewModel.cs
namespace MVC.Models
{
    public class VehiculoViewModel
    {
        public int IdVehiculo { get; set; }
        public string Matricula { get; set; } = null!;
        public string Marca { get; set; } = null!;
        public string Color { get; set; } = null!;
        public decimal Alquiler { get; set; }
        public int GarajeIdGaraje { get; set; }
    }
}

CanellaPrueba/MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Models;
using System.Diagnostics;

namespace MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CanellaPrueba/MVC/Controllers/VehiculoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVC.Models;
using Newtonsoft.Json;
using System.Text;

namespace MVC.Controllers
{
    public class VehiculoController : Controller
    {
        Uri Baseurl = new Uri("https://localhost:7256/api");
        HttpClient client;

        public VehiculoController()
        {
            client = new HttpClient();
            client.BaseAddress = Baseurl;
        }

        public ActionResult Index()
        {
            List<VehiculoViewModel> modelList = new List<VehiculoViewModel>();
            HttpResponseMessage responseMessage = client.GetAsync(client.BaseAddress + "/Vehiculoes").Result;
            if (responseMessage.IsSuccessStatusCode)
            {
                string data = responseMessage.Content.ReadAsStringAsync().Result;
                if (data != null)
                {
                    modelList = JsonConvert.DeserializeObject<List<VehiculoViewModel>>(data);

                }
            }
            return View(modelList);
        }

        /*public ActionResult Create()
        {
            List<GarajeViewModel> modelList = new List<GarajeViewModel>();
            HttpResponseMessage responseMessage = client.GetAsync(client.BaseAddress + "/Garajes").Result;
            if (responseMessage.IsSuccessStatusCode)
            {
                string data = responseMessage.Content.ReadAsStringAsync().Result;
                if (data != null)
                {
                    modelList = JsonConvert.DeserializeObject<List<GarajeViewModel>>(data);
                    List<SelectListItem> items = new List<SelectListItem>();
                    foreach(var item in modelList)
                    {
                        items.Add(new SelectListItem { Text = item.Nombre, Value = item.IdGaraje.ToString() });
                    }
                    ViewBag.garaje = items;
                }
            }
            return View();
        }*/

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(VehiculoViewModel model)
        {
            string data = JsonConvert.SerializeObject(model);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage responseMessage = client.PostAsync(client.BaseAddress + "/Vehiculoes", content).Result;
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Edit(int id)
        {
            VehiculoViewModel vehiculo = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7256/api/");
                //HTTP GET
                var responseTask = client.GetAsync("Vehiculoes/" + id.ToString());
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<VehiculoViewModel>();
                    readTask.Wait();

                    vehiculo = readTask.Result;
                }
            }
            return View(vehiculo);
        }

        [HttpPost]
        public ActionResult Edit(VehiculoViewModel model)
        {
            string data = JsonConvert.SerializeObject(model);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage responseMessage = client.PutAsync(client.BaseAddress + "/Vehiculoes", content).Result;
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7256/api/");

                //HTTP DELETE
                var deleteTask = client.DeleteAsync("Vehiculoes/" + id.ToString());
                deleteTask.Wait();

                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                {

                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Index");
        }
    }
}

CanellaPrueba/MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CanellaPrueba/MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehiculo" asp-action="Index">Vehiculos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CanellaPrueba/MVC/Views/Vehiculo/Create.cshtml
@model MVC.Models.VehiculoViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>VehiculoViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="IdVehiculo" class="control-label"></label>
                <input asp-for="IdVehiculo" class="form-control" />
                <span asp-validation-for="IdVehiculo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Matricula" class="control-label"></label>
                <input asp-for="Matricula" class="form-control" />
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alquiler" class="control-label"></label>
                <input asp-for="Alquiler" class="form-control" />
                <span asp-validation-for="Alquiler" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GarajeIdGaraje" class="control-label"></label>
                <input asp-for="GarajeIdGaraje" class="form-control" />
                <span asp-validation-for="GarajeIdGaraje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CanellaPrueba/MVC/Views/Vehiculo/Edit.cshtml
@model MVC.Models.VehiculoViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>VehiculoViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="IdVehiculo" class="control-label"></label>
                <input asp-for="IdVehiculo" class="form-control" />
                <span asp-validation-for="IdVehiculo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Matricula" class="control-label"></label>
                <input asp-for="Matricula" class="form-control" />
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alquiler" class="control-label"></label>
                <input asp-for="Alquiler" class="form-control" />
                <span asp-validation-for="Alquiler" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GarajeIdGaraje" class="control-label"></label>
                <input asp-for="GarajeIdGaraje" class="form-control" />
                <span asp-validation-for="GarajeIdGaraje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CanellaPrueba/MVC/Views/Vehiculo/Index.cshtml
@model IEnumerable<MVC.Models.VehiculoViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th hidden>
                @Html.DisplayNameFor(model => model.IdVehiculo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Matricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Alquiler)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.GarajeIdGaraje)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td hidden>
                @Html.DisplayFor(modelItem => item.IdVehiculo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Matricula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Alquiler)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.GarajeIdGaraje)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.IdVehiculo }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.IdVehiculo })
            </td>
        </tr>
}
    </tbody>
</table>